Make ILB count configurable and increase default to 2.
kubernetes/perf-tests pull request #1802
Opened 2021-05-12 22:04 UTC by prameshj

**What type of PR is this?**

**What this PR does / why we need it**:
This PR makes the number of ILB services in the scale test to be configurable.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

2021-05-12 22:05 UTC, prameshj commented
Eventually all tests will start using the template being added in https://github.com/kubernetes/perf-tests/pull/1785

Until we maintain the current config file, it will be useful to configure the ILBs being deployed.

cc @freehan 

/assign @tosi3k @jkaniuk

2021-05-13 08:01 UTC, tosi3k requested changes
One minor remark, other than that LGTM.

2021-05-13 15:28 UTC, prameshj commented on clusterloader2/testing/l4ilb/config.yaml
> +{{$LARGE_BACKEND_LB_SERVICE_COUNT := DefaultParam .LARGE_BACKEND_LB_SERVICE_COUNT 2}}
Done. Thanks!

2021-05-13 15:30 UTC, tosi3k commented
/lgtm
/assign @jkaniuk

2021-05-13 17:32 UTC, jkaniuk commented
/approve

2021-05-13 17:34 UTC, merged