Add network policy enforcement latency measurement to load test
kubernetes/perf-tests pull request #2251
Opened 2023-04-14 12:19 UTC by dlapcevic

Integrate network policy enforcement latency measurement (https://github.com/kubernetes/perf-tests/pull/2234) with the CL2 load test.

/kind feature

2023-04-14 12:19 UTC, dlapcevic commented
/assign @marseel

2023-05-22 12:29 UTC, tosi3k requested changes

2023-05-22 12:29 UTC, tosi3k commented on clusterloader2/testing/load/deployment.yaml
>  {{end}}
If we change the indentation, please indent this line as well for consistency's sake.

2023-06-06 12:59 UTC, dlapcevic commented on clusterloader2/testing/load/modules/network-policy/net-policy-enforcement-latency.yaml
> +{{if $ENABLE_NETWORK_POLICY_ENFORCEMENT_LATENCY_TEST}}
Done

2023-06-06 12:59 UTC, dlapcevic commented on clusterloader2/testing/load/modules/network-policy/net-policy-metrics.yaml
> +{{if $ENABLE_NETWORK_POLICY_ENFORCEMENT_LATENCY_TEST}}
Done

2023-06-12 09:39 UTC, dlapcevic commented on clusterloader2/testing/load/modules/network-policy/net-policy-metrics.yaml
> +{{$ENABLE_NETWORK_POLICY_ENFORCEMENT_LATENCY_TEST := DefaultParam .CL2_ENABLE_NETWORK_POLICY_ENFORCEMENT_LATENCY_TEST false}}
Done.

2023-06-12 14:34 UTC, dlapcevic commented
I resolved the comments and added thresholds to the `GenericPrometheusQuery` in `net-policy-metrics.yaml`.

2023-06-12 15:43 UTC, tosi3k commented
/lgtm
/hold

Feel free to unhold after you test the latest version of this PR in a manual run.

2023-06-12 16:24 UTC, dlapcevic commented
Latest run passed as well.

/hold cancel

2023-06-12 18:01 UTC, merged